// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkhj0O-qzOTqHVzNcLlU6-rf7wwaEoTxY',
    appId: '1:330706696960:web:e336577fe8019597d111e5',
    messagingSenderId: '330706696960',
    projectId: 'flutterapp-28d6a',
    authDomain: 'flutterapp-28d6a.firebaseapp.com',
    storageBucket: 'flutterapp-28d6a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_mZlpNx9Fqa7TgUPIMWDaFTNG14qivgs',
    appId: '1:330706696960:android:f2d9e8771d1f9948d111e5',
    messagingSenderId: '330706696960',
    projectId: 'flutterapp-28d6a',
    storageBucket: 'flutterapp-28d6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbD3EsaliB6S8WMBaLdeoMy87SEUUHu7k',
    appId: '1:330706696960:ios:fd4ae3b6cc43cd76d111e5',
    messagingSenderId: '330706696960',
    projectId: 'flutterapp-28d6a',
    storageBucket: 'flutterapp-28d6a.appspot.com',
    iosBundleId: 'com.example.flutterprojem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbD3EsaliB6S8WMBaLdeoMy87SEUUHu7k',
    appId: '1:330706696960:ios:fd4ae3b6cc43cd76d111e5',
    messagingSenderId: '330706696960',
    projectId: 'flutterapp-28d6a',
    storageBucket: 'flutterapp-28d6a.appspot.com',
    iosBundleId: 'com.example.flutterprojem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkhj0O-qzOTqHVzNcLlU6-rf7wwaEoTxY',
    appId: '1:330706696960:web:7662b8bd0ae85214d111e5',
    messagingSenderId: '330706696960',
    projectId: 'flutterapp-28d6a',
    authDomain: 'flutterapp-28d6a.firebaseapp.com',
    storageBucket: 'flutterapp-28d6a.appspot.com',
  );
}
